
spring:
  h2:
    console:
      enabled: true
      path: /h2     # Context path
  datasource:
    url: jdbc:h2:mem:test     # JDBC URL
  jpa:
    hibernate:
      ddl-auto: update  # 스키마 자동 생성
    show-sql: true      # SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # SQL pretty print
  sql:
    init:
      schema-locations: classpath*:db/h2/schema.sql
logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG